language: java
jdk:
  - openjdk8
branches:
  only:
    - main

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_install:
  - chmod +x gradlew
  - zip -r freelec-springboot2-webservice * #해당 디렉토리에 있는 모든 요소들을 zip으로 묶음
  - mkdir -p deploy #zip에 포함시킬 파일들을 담을 디렉토리 생성
  - mv freelec-springboot2-webservice.zip deploy/freelec-springboot2-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: sshan96-springboot-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근 private
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deploy: true

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - sshan96@naver.com